### PR TITLE
Add channel support to mac and linux

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by emilyrose** [comment]
Hey, this looks pretty good!

Give me a chance to test it out and I will merge, unless @mauricesvay has any objections!

Thanks!

**Comment by mauricesvay** [comment]
I've seen APs use multiple channels. If you can test that it doesn't break the parsing that would be great. No objections otherwise :)

**Comment by brycekahle** [comment]
If they get reported as `2,6` for example then that is what would be returned.

**Comment by brycekahle** [comment]
Added some tests to verify behavior

**Comment by brycekahle** [comment]
I'm going to re-open this PR under a branch

**Pull request closed without merging**
